version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql